consul:
    hostname: consul
    image: qnib/alpn-consul
    environment:
    - DC_NAME=dc1
    - CONSUL_BOOTSTRAP_EXPECT=1
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zkui:
    hostname: zkui
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zkui
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper0:
    hostname: zookeeper0
    dns: 127.0.0.1
    image: qnib/zookeeper
    #volumes:
    #- opt/qnib/zookeeper/bin/:/opt/qnib/zookeeper/bin/
    environment:
    - DC_NAME=dc1
    - MYID=1
    #- START_ZOOKEEPER=false
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    ports:
    - 2181:2181
    privileged: true

zookeeper1:
    hostname: zookeeper1
    dns: 127.0.0.1
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    - MYID=2
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    privileged: true

zookeeper2:
    hostname: zookeeper2
    dns: 127.0.0.1
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    - MYID=3
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    privileged: true

kafka0:
    hostname: kafka0
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/kafka
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    - zookeeper0:zookeeper
    privileged: true

kafka1:
    hostname: kafka1
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/kafka
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    - zookeeper0:zookeeper
    privileged: true

kafkaMonitor:
    hostname: kafka-monitor
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/kafka-monitor
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    links:
    - consul:consul
    - kafka0:kafka
    ports:
    - 8080:8080
    privileged: true

logstash:
    hostname: logstash
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/logstash:trunk
    volumes:
    - ./ls_conf/:/etc/logstash/conf.d/
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_FILE=true
    links:
    - consul:consul
    - kafka0:kafka
    privileged: true

